// <auto-generated />
namespace Khobzatna.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingismonytodonotiontype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingismonytodonotiontype));
        
        string IMigrationMetadata.Id
        {
            get { return "201808091916366_adding is mony to donotion type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
